# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /agent@habitat.simulator.agent_0: agent_base
  - /habitat/simulator/sim_sensors:
    - head_depth_sensor
  - /habitat/task/rearrange: close_cab
  - /habitat/dataset/rearrangement: replica_cad
  - _self_

habitat:
  gym:
    auto_name: CloseCab
    obs_keys:
      - robot_head_depth
      - joint
      - ee_pos
      - is_holding
      - relative_resting_position
  environment:
    max_episode_steps: 200
  simulator:
    type: RearrangeSim-v0
    additional_object_paths:
    - data/objects/ycb/configs/
    debug_render_goal: False
    concur_render: True
    auto_sleep: True
    agent_0:
      radius: 0.3
      robot_urdf: ./data/robots/hab_fetch/robots/hab_suction_v2.urdf
      robot_type: FetchSuctionRobot
    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True
  dataset:
    data_path: data/datasets/replica_cad/rearrange/v1/{split}/in_drawer_1k_100.json.gz
