# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: depthp_head_rgb_third_agent
  - /habitat/task/rearrange: drop_test
  - /habitat/dataset/rearrangement: floorplanner
  - _self_

habitat:
  gym:
    auto_name: Pick
    obs_keys:
      - robot_head_depth
  environment:
    max_episode_steps: 1
  simulator:
    type: TestSim-v0
    additional_object_paths:
      - data/objects/amazon_berkeley/configs/
      - data/objects/google_object_dataset/configs/
    debug_render_goal: False
    debug_render: False
    needs_markers: False
    concur_render: True
    auto_sleep: True
    requires_textures: False
    kinematic_mode: True
    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True

  dataset:
    data_path: data/datasets/floorplanner/rearrange/v1/{split}/categorical_rearrange_easy.json.gz
    type: ObjectRearrangeDataset-v0