# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /agent@habitat.simulator.agent_0: agent_base
  - /habitat/simulator/sim_sensors:
    - head_depth_sensor
  - /habitat/task/rearrange: nav_to_obj
  - /habitat/dataset/rearrangement: replica_cad
  - _self_

habitat:
  gym:
    auto_name: NavToObj
    obs_keys:
      - robot_head_depth
      - goal_to_agent_gps_compass
      - joint
  environment:
    max_episode_steps: 400
  simulator:
    type: RearrangeSim-v0
    additional_object_paths:
      - data/objects/ycb/configs/
    debug_render_goal: False
    agent_0:
      radius: 0.3
      robot_urdf: ./data/robots/hab_fetch/robots/hab_suction_v2.urdf
      robot_type: FetchSuctionRobot
    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True
    needs_markers: false
  dataset:
    data_path: data/datasets/replica_cad/rearrange/v1/{split}/rearrange_easy.json.gz
