# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /agent@habitat.simulator.agent_0: humanoid_agent_base
  - /habitat/simulator/sim_sensors:
    - head_rgb_sensor
    - head_depth_sensor
    - third_rgb_sensor
    - third_depth_sensor
  - /habitat/task/rearrange: play
  - /habitat/dataset/rearrangement: replica_cad
  - _self_

# Config for empty task to explore the scene.
habitat:
  environment:
    max_episode_steps: 0
  task:
    actions:
      walk_action:
        type: "WalkAction"
      humanjoint_action:
        type: "HumanJointAction"
      stop_action:
        type: "StopAction"

      grab_right_action:
        type: "GrabRightAction"
      grab_left_action:
        type: "GrabLeftAction"
      release_left_action:
        type: "ReleaseLeftAction"
      release_right_action:
        type: "ReleaseRightAction"

  simulator:
    type: RearrangeSim-v0
    seed: 100
    additional_object_paths:
      - "data/objects/ycb/configs/"
    agent_0:
      is_set_start_state: False
      radius: 0.3
      robot_urdf: '/Users/xavierpuig/Documents/human_sim_data/amass_male.urdf'
      ik_arm_urdf: '/Users/xavierpuig/Documents/human_sim_data/amass_male.urdf'
      robot_type: 'AmassHuman'
      amass_path: '/Users/xavierpuig/Documents/human_sim_data/amass_smpl_h/'
      body_model_path: '/Users/xavierpuig/Documents/human_sim_data/smplh/male/model.npz'
      human_type: "AmassHuman"
      sim_sensors:
        third_rgb_sensor:
          height: 212
          width: 120
        third_depth_sensor:
          height: 212
          width: 120

    habitat_sim_v0:
      enable_physics: True
  dataset:
    data_path: data/datasets/replica_cad/rearrange/v1/{split}/all_receptacles_10k_1k.json.gz
