# @package _global_
defaults:
  - /habitat/task/actions:
    - pddl_apply_action
    - oracle_nav_action
    - arm_action
    - base_velocity
    - rearrange_stop
habitat:
  gym:
    obs_keys:
      - robot_head_depth
      - relative_resting_position
      - obj_start_sensor
      - obj_goal_sensor
      - obj_start_gps_compass
      - obj_goal_gps_compass
      - joint
      - is_holding
      - ee_pos
      - localization_sensor
  simulator:
    habitat_sim_v0:
      allow_sliding: True


habitat_baselines:
  rl:
    policy:
      hierarchical_policy:
        # Override to use the oracle navigation skill.
        use_skills:
          nav: "oracle_nav"
          nav_to_receptacle: "oracle_nav"
        defined_skills:
          oracle_nav:
            skill_name: "OracleNavPolicy"
            obs_skill_inputs: ["obj_start_sensor", "abs_obj_start_sensor", "obj_goal_sensor", "abs_obj_goal_sensor"]
            max_skill_steps: 300
