---
    dataset_path: "data/fpss/hssd-hab-uncluttered.scene_dataset_config.json"
    additional_object_paths:
    - data/objects/ycb/configs/
    scene_sets:
      - name: "train"
        included_substrings:
          - "102817140"
      - name: "val"
        included_substrings:
          - "102817140"
      - name: "test"
        included_substrings:
          - "102817140"

    object_sets:
      - name: "ycb_hab2"
        included_substrings:
          - "002_master_chef_can"
          - "003_cracker_box"
          - "004_sugar_box"
          - "005_tomato_soup_can"
          - "007_tuna_fish_can"
          - "008_pudding_box"
          - "009_gelatin_box"
          - "010_potted_meat_can"
          - "024_bowl"
        excluded_substrings: []
    receptacle_sets:
      - name: "all"
        included_object_substrings:
          - ""
        excluded_object_substrings: []
        included_receptacle_substrings:
          - ""
        excluded_receptacle_substrings: []

    scene_sampler:
      type: scene_balanced
      params:
        scene_sets:
        - train
        #- val
        #- test

    object_samplers:
    - name: any
      type: uniform
      params:
        object_sets:
        - ycb_hab2
        receptacle_sets:
        - all
        num_samples:
        - 5
        - 10
        orientation_sampling: up
        nav_to_min_distance: 1.5
        constrain_to_largest_nav_island: True

    object_target_samplers:
    - name: any_targets
      type: uniform
      params:
        object_samplers:
        - any
        receptacle_sets:
        - all
        num_samples:
        - 2
        - 2
        orientation_sampling: up
        nav_to_min_distance: 1.5
        constrain_to_largest_nav_island: True

    correct_unstable_results: True

    regenerate_new_mesh: True
    agent_radius: 0.25
    agent_height: 1.41
    agent_max_climb: 0.01

    check_navigable: True
    navmesh_offset: [[0, 0], [0, 0.15], [0, -0.15]]
    max_collision_rate_for_navigable: 0.3
    angle_threshold: 0.05
    angular_velocity: 1.0
    distance_threshold: 0.25
    linear_velocity: 1.0

    gpu_device_id: 0
