# @package habitat.simulator.agents.spot_agent_jaw_sensor_rgb
defaults:
  - /habitat/simulator/sim_sensors@sim_sensors.jaw_depth_sensor: jaw_depth_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.jaw_rgb_sensor: jaw_rgb_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.jaw_panoptic_sensor: jaw_panoptic_sensor

sim_sensors:
  jaw_depth_sensor:
    height: 240
    width: 228
    hfov: 60
    min_depth: 0.0
    max_depth: 1.7
  jaw_rgb_sensor:
    height: 240
    width: 228
    hfov: 60
  jaw_panoptic_sensor:
    height: 240
    width: 228
    hfov: 60