# @package habitat.simulator.agents.spot_agent
defaults:
  - /habitat/simulator/sim_sensors@sim_sensors.arm_rgb_sensor: arm_rgb_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.arm_depth_sensor: arm_depth_sensor

sim_sensors:
  arm_rgb_sensor:
    height: 480
    width: 640
    hfov: 47
  arm_depth_sensor:
    height: 240
    width: 228
    hfov: 60
    min_depth: 0.0
    max_depth: 1.7
