# @package habitat.simulator.agents.spot_agent_jaw_tilt_sensor
defaults:
  - /habitat/simulator/sim_sensors@sim_sensors.jaw_depth_tilt_sensor: jaw_depth_tilt_sensor

sim_sensors:
  jaw_depth_tilt_sensor:
    height: 240
    width: 228
    hfov: 60
    min_depth: 0.0
    max_depth: 1.7
