# @package habitat.simulator.agents.human
radius: 0.3
articulated_agent_urdf: 'data/humanoids/humanoid_data/armatures/human_armature.urdf'
articulated_agent_type: 'KinematicHumanoid'
rest_pose_data_path: 'data/humanoids/humanoid_data/standing_pose_smplx.pkl'
motion_data_path: "data/humanoids/humanoid_data/walking_motion_processed_smplx.pkl"
sim_sensors:
  head_rgb_sensor:
    height: 128
    width: 128
  head_depth_sensor:
    height: 128
    width: 128
  arm_depth_sensor:
    height: 128
    width: 128
  arm_rgb_sensor:
    height: 128
    width: 128
