# @package habitat.simulator.agents.human
radius: 0.3
articulated_agent_urdf: 'data/humanoids/humanoid_data/female2_0.urdf'
articulated_agent_type: 'KinematicHumanoid'
motion_data_path: "data/humanoids/humanoid_data/walking_motion_processed_smplx.pkl"
sim_sensors:
  head_rgb_sensor:
    height: 224
    width: 224
  head_depth_sensor:
    height: 224
    width: 224
