# @package habitat.simulator.agents.spot
defaults:
  - agent_base
  - _self_

radius: 0.25
height: 1.41
articulated_agent_type: "SpotRobot"
articulated_agent_urdf: data/robots/hab_spot_arm/urdf/hab_spot_arm.urdf
sim_sensors:
  arm_rgb_sensor:
    height: 480
    width: 640
    hfov: 47
  arm_depth_sensor:
    height: 240
    width: 228
    hfov: 60
    min_depth: 0.0
    max_depth: 1.7
  arm_panoptic_sensor:
    height: 240
    width: 228
    hfov: 60
  head_stereo_right_depth_sensor:
    height: 212
    width: 120
    hfov: 58
    min_depth: 0.0
    max_depth: 3.5
  head_stereo_left_depth_sensor:
    height: 212
    width: 120
    hfov: 58
    min_depth: 0.0
    max_depth: 3.5
