# @package _global_

# Extends the `rl_hierarchical` config to use an oracle navigation action.
# Several things change to support the oracle navigation:
# - Adding the oracle navigation action
# - Add sliding.
# - Use the oracle navigation skill.

defaults:
  - rl_hierarchical_oracle_nav_spot_fp
  - /habitat/task/actions:
    - oracle_nav_spot_action
  - _self_

habitat:
  task:
    actions:
      oracle_nav_spot_action:
        type: OracleNavSpotAction
        spawn_max_dist_to_obj: -1.0
        # For noncylinder action
        allow_dyn_slide: True
        enable_rotation_check_for_dyn_slide: False
        collision_threshold: 0.02
        navmesh_offset: [[0.0, 0.0], [0.25, 0.0], [-0.25, 0.0]]
        navmesh_offset_check: [[0.0, 0.0], [0.25, 0.0], [-0.25, 0.0]]
        enable_lateral_move: False
    robot_at_thresh: 3.0
    enable_teleport_action: False
