# @package _global_

# Extends the `rl_hierarchical_oracle_nav` config to use the human avatar.
# Several things change to support the oracle navigation:
# - Add ignore_grip parameter
# - Add sliding.
# - Use the oracle navigation skill.

defaults:
  - rl_hierarchical_oracle_nav
  - /habitat/task/lab_sensors:
    - relative_resting_pos_sensor
    - target_start_sensor
    - goal_sensor
    - humanoid_joint_sensor
    - is_holding_sensor
    - end_effector_sensor
    - target_start_gps_compass_sensor
    - target_goal_gps_compass_sensor
    - localization_sensor
  - override /habitat/task/actions:
    - base_velocity
    - rearrange_stop
    - oracle_nav_action
  - override /habitat/task/rearrange: rearrange_easy_humanoid
  - _self_

habitat:
  task:
    actions:
      oracle_nav_action:
        motion_control: human_joints
        spawn_max_dist_to_obj: 1.7
  gym:
    obs_keys:
      - head_depth
      - relative_resting_position
      - obj_start_sensor
      - obj_goal_sensor
      - obj_start_gps_compass
      - obj_goal_gps_compass
      - humanoid_joint_sensor
      - localization_sensor
      - is_holding
  simulator:
    agents:
      main_agent:
        articulated_agent_urdf: 'data/humanoids/humanoid_data/amass_male.urdf'
        articulated_agent_type: KinematicHumanoid
        motion_data_path: "data/humanoids/humanoid_data/walking_motion_processed.pkl"

habitat_baselines:
  rl:
    policy:
      hierarchical_policy:
        defined_skills:
          nav_to_obj:
            ignore_grip: True
            pddl_action_names: ["nav", "nav_to_receptacle_by_name"]
          open_cab:
            ignore_grip: True
          open_fridge:
            ignore_grip: True
          close_cab:
            ignore_grip: True
          close_fridge:
            ignore_grip: True
          pick:
            ignore_grip: True
          place:
            ignore_grip: True
          wait:
            ignore_grip: True
          reset_arm:
            skill_name: "NoopSkillPolicy"
            max_skill_steps: 1
            ignore_grip: True
            force_end_on_timeout: False
