# @package _global_

# Extends the `rl_hierarchical` config to use an oracle navigation action.
# Several things change to support the oracle navigation:
# - Adding the oracle navigation action
# - Add sliding.
# - Use the oracle navigation skill.

defaults:
  - rl_hierarchical
  - /habitat/task/actions:
    - oracle_nav_action
  - override /habitat_baselines/rl/policy/hierarchical_policy/defined_skills: oracle_skills_nogrip
  - override /habitat/task/rearrange: rearrange_easy_humanoid
  - _self_

habitat:
  task:
    actions:
      oracle_nav_action:
        motion_control: human_joints
        spawn_max_dist_to_obj: 1.7
  gym:
    obs_keys:
      - robot_head_depth
      - relative_resting_position
      - obj_start_sensor
      - obj_goal_sensor
      - obj_start_gps_compass
      - obj_goal_gps_compass
      - joint
      - is_holding
      - ee_pos
      - localization_sensor
  simulator:
    habitat_sim_v0:
      allow_sliding: True

    agents:
      main_agent:
        agent_urdf: 'data/humanoids/humanoid_data/amass_male.urdf'
        agent_type: KinematicHumanoid


habitat_baselines:
  num_environments: 1
  rl:
    policy:
      hierarchical_policy:
        # Override to use the oracle navigation skill.
        defined_skills:
          nav_to_obj:
            skill_name: "OracleNavPolicy"
            obs_skill_inputs: ["obj_start_sensor", "abs_obj_start_sensor", "obj_goal_sensor", "abs_obj_goal_sensor"]
            max_skill_steps: 300
            ignore_grip: True
            pddl_action_names: ["nav", "nav_to_receptacle_by_name"]
