# @package _global_
# Pick and place are instantaneous skills,
# where environment is set to final state.
# Navigation is kinematically simulated.

defaults:
  - /benchmark/rearrange: rearrange_easy_human
  - /habitat_baselines: habitat_baselines_rl_config_base
  - /habitat_baselines/rl/policy/obs_transforms:
    - add_virtual_keys_base
  - /habitat_baselines/rl/policy: hierarchical_tp_noop_onav_human
  - /habitat/task/actions:
    - pddl_apply_action
    - humanjoint_action
    - human_nav_action
    - rearrange_stop
  
  - override /habitat/simulator/agents@habitat.simulator.agents.main_agent: depth_head_human_vis
  - _self_

habitat:
  gym:
    obs_keys:
      - robot_head_depth
      - relative_resting_position
      - obj_start_sensor
      - obj_goal_sensor
      - obj_start_gps_compass
      - obj_goal_gps_compass
      - human_joint
      - is_holding
      - localization_sensor
  simulator:
    agents:
      main_agent:
        agent_urdf: 'data/human_sim_data/amass_male.urdf'
        ik_arm_urdf: 'data/human_sim_data/amass_male.urdf'
        agent_type: 'AmassHuman'
        draw_fps_human: 15
        amass_path: 'data/human_sim_data/amass_smpl_h/'
        body_model_path: 'data/human_sim_data/smplh/male/model.npz'


habitat_baselines:
  verbose: False
  trainer_name: "ddppo"
  torch_gpu_id: 0
  rollout_storage: "HrlRolloutStorage"
  updater_name: "HrlPPO"
  distrib_updater_name: "HrlDDPPO"
  video_fps: 30
  eval_ckpt_path_dir: ""
  num_environments: 1
  video_render_views:
    - "third_rgb_sensor"
  writer_type: 'tb'
  checkpoint_folder: "data/new_checkpoints"
  num_updates: -1
  total_num_steps: 1.0e8
  log_interval: 10
  num_checkpoints: 20
  force_torch_single_threaded: True
  eval_keys_to_include_in_name: ['reward', 'force', 'composite_success']
  load_resume_state_config: False

  eval:
    use_ckpt_config: False
    should_load_ckpt: False
    video_option: ["disk"]

  rl:
    policy:
      hierarchical_policy:
        high_level_policy:
          name: "NeuralHighLevelPolicy"
          allow_other_place: False
          hidden_dim: 512
          use_rnn: True
          rnn_type: 'LSTM'
          backbone: resnet18
          normalize_visual_inputs: False
          num_rnn_layers: 2
          policy_input_keys:
            - "robot_head_depth"
    ppo:
      # ppo params
      clip_param: 0.2
      ppo_epoch: 2
      num_mini_batch: 2
      value_loss_coef: 0.5
      entropy_coef: 0.0001
      lr: 2.5e-4
      eps: 1e-5
      max_grad_norm: 0.2
      num_steps: 128
      use_gae: True
      gamma: 0.99
      tau: 0.95

    ddppo:
      sync_frac: 0.6
      # The PyTorch distributed backend to use
      distrib_backend: NCCL
      # Visual encoder backbone
      pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
      # Initialize with pretrained weights
      pretrained: False
      # Initialize just the visual encoder backbone with pretrained weights
      pretrained_encoder: False
      # Whether the visual encoder backbone will be trained.
      train_encoder: True
      # Whether to reset the critic linear layer
      reset_critic: False
      # Model parameters
      backbone: resnet18
      rnn_type: LSTM
      num_recurrent_layers: 2
