# @package _global_

# Extends the `rl_hierarchical_oracle_nav` config to use the human avatar.
# Several things change to support the oracle navigation:
# - Add ignore_grip parameter
# - Add sliding.
# - Use the oracle navigation skill.

defaults:
  - rl_hierarchical_oracle_nav_human
  - override /habitat_baselines/rl/policy: hl_neural
  - override /habitat_baselines/rl/policy/hierarchical_policy/defined_skills: oracle_skills
  - _self_
max_episode_steps: 500
num_environments: 4
kinematic_mode: True
step_physics: False
evaluate: False

env_set:
  MAGNUM_LOG: quiet 
  HABITAT_SIM_LOG: quiet

habitat_baselines:
  evaluate: ${evaluate}
  writer_type: 'wb'
  wb:
    project_name: 'hab3'
    entity: 'andrew-colab'
  num_environments: ${num_environments}

habitat:
  task:
    measurements:
      composite_success:
        must_call_stop: False
      force_terminate:
        max_accum_force: -1.0
        max_instant_force: -1.0


  environment:
    max_episode_steps: ${max_episode_steps}

  simulator:
    kinematic_mode: ${kinematic_mode}
    ac_freq_ratio: 1
    step_physics: ${step_physics}