name: Hello World 1
runs:
  using: composite
  steps:
  - name: Print Hello World
    run: echo "Hello World"
    shell: bash
  - name: Setup miniconda
    uses: conda-incubator/setup-miniconda@v3.0.1
    with:
      miniconda-version: "latest"
      python-version: "3.10"
  - name: Install conda and dependencies
    run: |-
      echo "Install conda and dependencies"
      conda create -n env_isaaclab python=3.10
      conda activate env_isaaclab