name: Hello World
on:
  pull_request: {}
  push:
    branches:
    - main
    tags: [ "v*" ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"