name: Hello World
on:
  push:
    branches:
      - main
jobs:
  hello-world:
    runs-on: 4-core-ubuntu-gpu-t4
    env:
      PYPI_LAB_UPLOAD_TOKEN: ${{ secrets.PYPI_LAB_UPLOAD_TOKEN }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Print Hello World
        run: echo "Hello World"