name: Hello World 1
runs:
  using: composite
  steps:
    - name: Print Hello World
      shell: bash
      run: |- 
      echo "Hello World"
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3.0.1
        with:
          miniconda-version: "latest"
          python-version: "3.9"
          activate-environment: "habitat"