name: Hello World 1
runs:
  using: composite
  steps:
  - name: Print Hello World
    run: echo "Hello World"
    shell: bash
  - name: Setup miniconda
    uses: conda-incubator/setup-miniconda@v3.0.1
    with:
      miniconda-version: "latest"
      python-version: "3.10"
  - name: Install conda and isaac lab 
    run: |-
      echo "Install conda and dependencies"
      conda create -n env_isaaclab python=3.10
      conda init
      source ~/.bashrc
      conda activate env_isaaclab
      pip install torch==2.5.1 --index-url https://download.pytorch.org/whl/cu118
      pip install isaacsim[all,extscache]==4.5.0 --extra-index-url https://pypi.nvidia.com
    shell: bash