# @package _global_

  defaults:
    - /habitat: habitat_config_base
    - /habitat/task: objectnav
    - /habitat/simulator/sim_sensors:
      - depth_sensor
      - rgb_sensor
      # - semantic_sensor
    - /habitat/dataset/objectnav: mp3d

  habitat:
    environment:
      max_episode_steps: 500

    simulator:
      turn_angle: 30
      tilt_angle: 30
      action_space_config: "v1"
      agent_0:
        sim_sensors:
          # semantic_sensor:
          #   width: 640
          #   height: 480
          #   hfov: 79
          #   position: [0, 0.88, 0]
          rgb_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 0.88, 0]
          depth_sensor:
            width: 640
            height: 480
            hfov: 79
            min_depth: 0.5
            max_depth: 5.0
            position: [0, 0.88, 0]
        height: 0.88
        radius: 0.18
      habitat_sim_v0:
        gpu_device_id: 0
        allow_sliding: False

    # task:
    #   type: ObjectNav-v1
    #   end_on_success: True
    #   reward_measure: "distance_to_goal_reward"
    #   success_measure: "spl"

    #   possible_actions: ["stop", "move_forward", "turn_left", "turn_right", "look_up", "look_down"]

    #   sensors: ['OBJECTgoal_sensor', 'compass_sensor', 'gps_sensor']
    #   goal_sensor_uuid: objectgoal

    #   measurements: ['distance_to_goal', 'success', 'spl', 'soft_spl', 'distance_to_goal_reward']

    #   distance_to_goal:
    #     distance_to: VIEW_POINTS
    #   success:
    #     success_distance: 0.1
