# @package habitat.task

defaults:
  - /habitat/task: task_config_base
  - /habitat/task/actions:
    - base_velocity
  - /habitat/task/measurements:
    - test_success
    - test_reward
  - _self_

type: TestTask-v0
base_angle_noise: 0.523599
constraint_violation_ends_episode: False
constraint_violation_drops_object: True
reward_measure: "test_reward"
success_measure: "test_success"
success_reward: 10.0
slack_reward: -0.005
end_on_success: True
desired_resting_position: [0.119, -0.383, 0.657]