# @package habitat

    defaults:
     # habitat_config_base is in the group habitat and @ nothing since we want it at the root
     - /habitat/habitat_config_base@
     - /camera_sensors/head_depth_sensor

    gym:
        auto_name: "Pick"
        obs_keys: ['robot_head_depth', 'obj_start_sensor', 'joint', 'is_holding', 'relative_resting_position']
    environment:
        max_episode_steps: 200
    dataset:
        type: RearrangeDataset-v0
        split: train
        data_path: data/datasets/replica_cad/rearrange/v1/{split}/all_receptacles_10k_1k.json.gz
        scenes_dir: "data/replica_cad/"
    task:
        type: RearrangePickTask-v0
        count_obj_collisions: True

        should_enforce_target_within_reach: False

        # In radians
        base_angle_noise: 0.15
        base_noise: 0.05
        force_regenerate: False

        constraint_violation_ends_episode: false
        constraint_violation_drops_object: True

        reward_measure: "rearrangepick_reward"
        success_measure: "rearrangepick_success"
        success_reward: 100.0
        slack_reward: -0.01
        end_on_success: True

        # If true, does not care about navigability or collisions with objects when spawning
        # robot
        easy_init: False
        state_sensors:
            target_start_sensor:
                # _target_: TargetStartSensor
                type: "TargetStartSensor"
                goal_format: "CARTESIAN"
                dimensionality: 3
            joint_sensor:
                type: "JointSensor"
                dimensionality: 7
            end_effector_sensor:
                type: "EEPositionSensor"
            is_holding_sensor:
                type: "IsHoldingSensor"
            relative_resting_pos_sensor:
                type: "RelativeRestingPositionSensor"
        measurements:
            robot_force:
                type: "RobotForce"
                min_force: 20.0
            force_terminate:
                type: "ForceTerminate"
                max_accum_force: 5000.0
                max_instant_force: -1
            end_effector_to_object_distance:
                type: "EndEffectorToObjectDistance"
            end_effector_to_rest_distance:
                type: "EndEffectorToRestDistance"
            did_pick_object:
                type: "DidPickObjectMeasure"
            num_steps:
                type: "NumStepsMeasure"
            did_violate_hold_constraint:
                type: "DidViolateHoldConstraintMeasure"
            pick_reward:
                type: "RearrangePickReward"
                dist_reward: 20.0
                succ_reward: 10.0
                pick_reward: 20.0
                drop_pen: 5.0
                wrong_pick_pen: 5.0
                use_diff: True
                drop_obj_should_end: True
                wrong_pick_should_end: True

                # General Rearrange Reward config
                constraint_violate_pen: 10.0
                force_pen: 0.001
                max_force_pen: 1.0
                force_end_pen: 10.0

            pick_success:
                type: "RearrangePickSuccess"
                ee_resting_success_threshold: 0.2

        actions:
            arm_action:
                type: "ArmAction"
                arm_controller: "ArmRelPosAction"
                grip_controller: SuctionGraspAction
                arm_joint_dimensionality: 7
                grasp_thresh_dist: 0.15
                disable_grip: False
                delta_pos_limit: 0.0125
                ee_ctrl_lim: 0.015

    simulator:
        additional_object_paths:
            - "data/objects/ycb/configs/"
        action_space_config: v0
        agents: ['agent_0']
        debug_render: False
        debug_render_goal: False
        needs_markers: False
        agent_0:
            height: 1.5
            radius: 0.3
            robot_urdf: ./data/robots/hab_fetch/robots/hab_suction.urdf
            robot_type: FetchSuctionRobot
            ik_arm_urdf: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
            camera_sensors:
                head_depth_sensor:
                    width: 256
                    height: 256
            # camera_sensors:
            #     head_depth_sensor:
            #         type: HabitatSimDepthSensor
            #         uuid: robot_head_depth
            #         width: 256
            #         height: 256
            #         min_depth: 0.0
            #         max_depth: 10.0
            #         normalize_depth: True
            #     # head_rgb_sensor:
            #     #     width: 700 #256
            #     #     height: 256
            #     # arm_depth_sensor:
            #     #     type: HabitatSimDepthSensor
            #     #     uuid: robot_arm_depth
            #     #     height: 128
            #     #     max_depth: 10.0
            #     #     min_depth: 0.0
            #     #     normalize_depth: true
            #     #     width: 128
            #     # arm_rgb_sensor:
            #     #     type: HabitatSimRGBSensor
            #     #     uuid: robot_arm_rgb
            #     #     height: 128
            #     #     width: 128

        # Agent setup
        ctrl_freq: 120.0
        ac_freq_ratio: 4
        forward_step_size: 0.25

        # Grasping
        hold_thresh: 0.2
        grasp_impulse: 10000.0

        default_agent_id: 0
        habitat_sim_v0:
            allow_sliding: False
            enable_physics: True
            gpu_device_id: 0
            gpu_gpu: False
            physics_config_file: ./data/default.physics_config.json
        type: RearrangeSim-v0
