# @package habitat.task

defaults:
  - /habitat/task: task_config_base
  - /habitat/task/actions:
    - arm_action
  - /habitat/task/measurements:
    - robot_force
    - force_terminate
    - end_effector_to_rest_distance
    - end_effector_to_object_distance
    - did_pick_object
    - pick_success
    - pick_reward
    - did_violate_hold_constraint
    - num_steps
  - /habitat/task/lab_sensors:
    - target_start_sensor
    - joint_sensor
    - is_holding_sensor
    - end_effector_sensor
    - relative_resting_pos_sensor

type: RearrangePickTask-v0
constraint_violation_ends_episode: False
constraint_violation_drops_object: True
reward_measure: "rearrangepick_reward"
success_measure: "rearrangepick_success"
success_reward: 100.0
end_on_success: True
#possible_actions:
#  - arm_action
actions:
  arm_action:
    grip_controller: SuctionGraspAction
