# @package habitat.task

defaults:
  - /habitat/task: task_config_base
  - /habitat/task/actions:
    - arm_action
    - base_velocity
    - empty
  - /habitat/task/measurements:
    - articulated_agent_force
    - force_terminate
    - articulated_agent_colls
    - collisions_terminate
    - end_effector_to_rest_distance
    - end_effector_to_object_distance
    - joint_to_rest_distance
    - did_pick_object
    - pick_success
    - pick_success_joint
    - pick_reward
  - /habitat/task/lab_sensors:
    - target_start_sensor
    - joint_sensor
    - is_holding_sensor
    - end_effector_sensor
    - relative_resting_pos_sensor
    - relative_resting_joint
  - _self_

# Config for empty task to explore the scene.
type: RearrangeEmptyTask-v0
count_obj_collisions: True
desired_resting_position: [0.45, 0.0, 0.43]

measurements:
  pick_reward:
    enable_vel_penality: 1.0
    force_pen: 0.01
    max_force_pen: 0.01
    force_end_pen: 1.0

  collisions_terminate:
    max_scene_colls: -1 #100.0


# Reach task config
render_target: True
ee_sample_factor: 0.8

# In radians
base_angle_noise: 0.0
base_noise: 0.0
constraint_violation_ends_episode: False

force_regenerate: True

actions:
  arm_action:
    grip_controller: "MagicGraspAction"
