defaults:
  - task_config_base
  - actions:
    - move_forward
    - turn_left
    - turn_right
    - answer
  - measurements:
    - distance_to_goal
    - episode_info
    - answer_accuracy
  - lab_sensors:
    - question_sensor

type: EQA-v0
