
defaults:
  - task_config_base
  - actions:
    - stop
    - move_forward
    - turn_left
    - turn_right
    - look_up
    - look_down
  - measurements:
    # - distance_to_goal_instance
    - distance_to_goal
    - success
    - spl
    - soft_spl
    - distance_to_goal_reward
    - top_down_map
  - lab_sensors:
    - multigoal_sensor
    - compass_sensor
    - gps_sensor
  - _self_


type: Goat-v1
end_on_success: True
reward_measure: "distance_to_goal_reward"
success_measure: "spl"


goal_sensor_uuid: objectgoal

measurements:
  # distance_to_goal_instance:
  #   distance_to: VIEW_POINTS
  distance_to_goal:
    distance_to: VIEW_POINTS
  success:
    success_distance: 0.25 # different for objectnav and langnav
