
defaults:
  - task_config_base
  - actions:
    - goat_sub-task_stop
    - move_forward
    - turn_left
    - turn_right
    - look_up
    - look_down
  - measurements:
    - goat_distance_to_sub-goal
    - goat_sub-task_success
    - goat_sub-task_spl
    # - soft_spl
    - goat_top_down_map
  - lab_sensors:
    - multigoal_sensor
    - compass_sensor
    - gps_sensor
  - _self_


type: Goat-v1
end_on_success: True # TODO: check
success_measure: "goat_sub-task_spl"


goal_sensor_uuid: objectgoal

measurements:
  goat_distance_to_sub-goal:
    distance_to: VIEW_POINTS
  goat_sub-task_success:
    success_distance: 0.25 # different for objectnav and langnav
