# @package habitat

  defaults:
    - /habitat/habitat_config_base@
    - /camera_sensors/rgb_sensor
    - /camera_sensors/depth_sensor
    - /measurements/top_down_map


  environment:
    max_episode_steps: 1000

  simulator:
    agent_0:
      camera_sensors:
        rgb_sensor:
          width: 256
          height: 256
        depth_sensor:
          width: 256
          height: 256

  task:
    type: Nav-v0

    end_on_success: True
    reward_measure: "distance_to_goal_reward"
    success_measure: "spl"

    state_sensors:
      imagegoal_sensor:
        type: ImageGoalSensor

    measurements:
      distance_to_goal:
        type: DistanceToGoal
        distance_to: POINT
      success:
        type: Success
        success_distance: 1.0
      spl:
        type: SPL
      soft_spl:
        type: SoftSPL
      distance_to_goal_reward:
        type: DistanceToGoalReward

    actions:
      stop:
        type: StopAction
      move_forward:
        type: MoveForwardAction
      turn_left:
        type: TurnLeftAction
      turn_right:
        type: TurnRightAction
