# @package habitat

  defaults:
    - /habitat/habitat_config_base@
    - /camera_sensors/rgb_sensor
    - /camera_sensors/depth_sensor

  environment:
    max_episode_steps: 1000

  simulator:
    turn_angle: 30
    tilt_angle: 30
    action_space_config: v1
    agent_0:
      camera_sensors:
        rgb_sensor:
          width: 640
          height: 480
          hfov: 79
          position: [0, 0.88, 0]
        depth_sensor:
          width: 640
          height: 480
          hfov: 79
          min_depth: 0.5
          max_depth: 5.0
          position: [0, 0.88, 0]
      height: 0.88
      radius: 0.18
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: False

  task:
    type: InstanceImageNav-v1
    end_on_success: True
    reward_measure: distance_to_goal_reward
    success_measure: spl

    actions:
      stop:
        type: StopAction
      move_forward:
        type: MoveForwardAction
      turn_left:
        type: TurnLeftAction
      turn_right:
        type: TurnRightAction
      look_up:
        type: LookUpAction
      look_down:
        type: LookDownAction


    state_sensors:
      instance_imagegoal_sensor:
        type: InstanceImageGoalSensor
      instance_imagegoal_hfov_sensor:
        type: InstanceImageGoalHFOVSensor
      compass_sensor:
        type:
      gps_sensor:
        type: GPSSensor
        dimensionality: 2


    goal_sensor_uuid: instance_imagegoal

    measurements:
      num_steps:
        type: NumStepsMeasure
      distance_to_goal:
        type: DistanceToGoal
        distance_to: VIEW_POINTS
      success:
        type: Success
        success_distance: 0.1
      spl:
        type: SPL
      soft_spl:
        type: SoftSPL
      distance_to_goal_reward:
        type: DistanceToGoalReward


  dataset:
    type: InstanceImageNav-v1
    split: train
    data_path: data/datasets/instance_imagenav/hm3d/v1/{split}/{split}.json.gz
    scenes_dir: data/scene_datasets/
