# @package _global_
defaults:
  - pick
  - /habitat/task/lab_sensors:
    - arm_depth_bbox_sensor
  - override /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: spot_agent
  - override /habitat/simulator/agents@habitat.simulator.agents.main_agent: spot
  - override /habitat/task/rearrange/actions: spot_base_arm_empty
  - _self_

habitat:
  task:
    measurements:
      end_effector_to_object_distance:
        if_consider_gaze_angle: True
        center_cone_vector: [0.0, 1.0, 0.0]
      pick_success:
        ee_resting_success_threshold: -1.0
    lab_sensors:
      arm_depth_bbox_sensor:
        height: 240
        width: 228
    actions:
      arm_action:
        arm_controller: "ArmRelPosKinematicAction"
        center_cone_vector: [0.0, 1.0, 0.0]
        auto_grasp: True
        should_clip: True
  simulator:
    kinematic_mode: True
    ac_freq_ratio: 1
    step_physics: False
