# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: imagenav
  - /agent@habitat.simulator.agent_0: rgbd_agent

habitat:
  environment:
    max_episode_steps: 1000
  simulator:
    agent_0:
      sim_sensors:
        rgb_sensor:
          width: 256
          height: 256
        depth_sensor:
          width: 256
          height: 256
