# @package _global_

defaults:
  - lang_rearrange_humanoid_only.yaml
  - _self_

habitat_hitl:
  window: ~
  networking:
    enable: True
    max_client_count: 1
    http_availability_server:
      enable: True
    client_max_idle_duration: 180.0
    enable_connections_by_default: False
  experimental:
    headless:
      do_headless: True

rearrange_v2:
  data_collection:
    output_file_name: "session"
    s3_path: "Phase_4/test/single/"
