name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello World Action
        uses: "./habitat-lab/.github/actions/install_isaac_deps"