name: Hello World Workflow
on:
  pull_request: {}
  push:
    branches:
    - main
    tags: [ "v*" ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello World Action
        uses: "./habitat-lab/.github/actions/install_isaac_deps"